# Explanation

1. We need to add `+ 1` to the `num_row` because of how Pascal Triagle works, which basically four items for row three, three items for row 2, etc

2. Then we initialize `previous_list` and `current_list`. We will modify the `previous_list` items and rewrite `current_list` items with its value. During initial initialization, you add 1 (one) as an item and multiply it by the row number that provided by funtion's argument **after the `+ 1` addition**. See example <a href="#scrollTo=dnnJJlQR3JbS&line=6&uniqifier=1">here</a>

3. We then do a double `for` loop, first for will take the **range** of `num_row`, while the second for loop will take the iteration of first for loop plus one.
  - **First for loop**: this to create a number of iterations equal to the length of the end result, as list has a 0 index value, we don't need to add `+ 1` because that already taken care at the very beginning
  - **Second for loop**: we took an interation from **first for loop** and **add it by one**, probably to avoid having range(0), which I would bet, not a valid argument

4. Add `if else` condition inside the second for loop
  - The `if` is to fill in the start and the end of the list, which is always has one as its value
  - The `else` is to fill in what's in between, which is an addition of current index (j) and the next index (j-1)

5. Lastly we will rewrite the `previous_list` with the `current_list`, which was an updated version

Problem: Find a Pascal value of any given row

In [1]:
def pascal_triangle(num_row):
    num_row += 1
    previous_list = [1] * num_row
    current_list = [1] * num_row
    
    for i in range(num_row):
        for j in range(i+1):
            if j == 0 or j == i:
                current_list[j] = previous_list[j]
            else:
                current_list[j] = previous_list[j-1] + previous_list[j]
        previous_list = current_list[:]
    return current_list

print(pascal_triangle(3))

[1, 3, 3, 1]

In [2]:
# Let's say we have three (3) as a input

arr = [1]
n = 3

arr * n

[1, 1, 1]